# KNN on LIWC


Import the required packages.

In [5]:
import os
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier

import pandas as pd
import pprint
from ast import literal_eval

Read the dataset, and create the data and label arrays.

In [6]:
corpus = pd.read_csv('gm_test_liwc_all.csv');

labels = []
for news in corpus['class']:
    labels.append(news)

del corpus['class']
data = corpus.values.tolist()

print "Total number of documents: " + str(len(data))

Total number of documents: 6294


## Training and Validation

In [7]:
#Stratified 10-cross fold validation with SVM and Multinomial NB 
      
kvalues = [2, 3, 10]
count = float(len(data))

for k in kvalues:

    print "*************************************************"
    print "Running validation on k = " + str(k)
    
    kf = StratifiedKFold(n_splits=k)

    
    print "\n"
    print "============================================="
    
    total = 0
    totalMat = np.zeros((2,2));

    for train_index, test_index in kf.split(data,labels):
        X_train = [data[i] for i in train_index]
        X_test = [data[i] for i in test_index]
        y_train = [labels[i] for i in train_index]
        y_test = [labels[i] for i in test_index]
        
        model = KNeighborsClassifier(n_neighbors=3)
        
        model.fit(X_train,y_train)
        
        result = model.predict(X_test)
        
        totalMat = totalMat + confusion_matrix(y_test, result)
        
        total = total+sum(y_test==result)
        
    print("totalMat: ")
    print(totalMat)
    print("total: ")
    print(total/count)

*************************************************
Running validation on k = 2


totalMat: 
[[ 3163.     8.]
 [   13.  3110.]]
total: 
0.996663489037
*************************************************
Running validation on k = 3


totalMat: 
[[ 3163.     8.]
 [   11.  3112.]]
total: 
0.996981251986
*************************************************
Running validation on k = 10


totalMat: 
[[ 3165.     6.]
 [    9.  3114.]]
total: 
0.997616777884
