# KNN


### Feature Extraction methods
TFIDF
Token Count
LIWC


### Description
The performances of these feature extraction methods are compared to identify which one has yields the best accuracies.

In [12]:
import os
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import StratifiedKFold

import pandas as pd
import pprint
from ast import literal_eval

In [13]:
corpus = pd.read_csv('gm_fake_or_real.csv');

In [14]:
data = []
labels = []
for news in corpus['text']:
    data.append(news)

for news in corpus['class']:
    labels.append(news)

print "Total number of articles: " + str(len(data))

Total number of articles: 6299


## Training and Validation

In [16]:
#Stratified 10-cross fold validation with SVM and Multinomial NB 
      
kvalues = [2, 3, 10]
count = float(len(data))

for k in kvalues:

    print "*************************************************"
    print "Running validation on k = " + str(k)
    
    kf = StratifiedKFold(n_splits=k)
    

    print "\n"
    print "============================================="
    print "Feature extraction: TFIDF\n"
    
    total = 0           # Accuracy measure
    totalMat = np.zeros((2,2));  # Confusion matrix
    
    for train_index, test_index in kf.split(data,labels):
        X_train = [data[i] for i in train_index]
        X_test = [data[i] for i in test_index]
        y_train = [labels[i] for i in train_index]
        y_test = [labels[i] for i in test_index]
    
        vectorizer = TfidfVectorizer(min_df=5,
                                     max_df = 0.8,
                                     sublinear_tf=True,
                                     use_idf=True,
                                     stop_words='english',
                                     token_pattern=ur'(?u)\b[^\W\d][^\W\d]+\b')

        train_corpus_tf_idf = vectorizer.fit_transform(X_train) 
        test_corpus_tf_idf = vectorizer.transform(X_test)
    
        model = KNeighborsClassifier(n_neighbors=3)

        model.fit(train_corpus_tf_idf,y_train)
        
        result = model.predict(test_corpus_tf_idf)
        
        totalMat = totalMat + confusion_matrix(y_test, result)
        
        total = total+sum(y_test==result)
                
    print("totalMat: ")
    print(totalMat)
    print("total: ")
    print(total/count)
    
    
    
    print "============================================="
    print "Feature extraction: Token Count"
    print "\n"
    
    total = 0           # Accuracy measure
    totalMat = np.zeros((2,2));  # Confusion matrix
    
    for train_index, test_index in kf.split(data,labels):
        X_train = [data[i] for i in train_index]
        X_test = [data[i] for i in test_index]
        y_train = [labels[i] for i in train_index]
        y_test = [labels[i] for i in test_index]
    
        vectorizer = CountVectorizer(min_df=5,
                                     max_df = 0.8,
                                     stop_words='english',
                                     token_pattern=ur'(?u)\b[^\W\d][^\W\d]+\b')
        train_corpus_tf_idf = vectorizer.fit_transform(X_train) 
        test_corpus_tf_idf = vectorizer.transform(X_test)
        
        model = KNeighborsClassifier(n_neighbors=3)

        model.fit(train_corpus_tf_idf,y_train)
        
        result = model.predict(test_corpus_tf_idf)
        
        totalMat = totalMat + confusion_matrix(y_test, result)
        
        total = total+sum(y_test==result)
                
    print("totalMat: ")
    print(totalMat)
    print("total: ")
    print(total/count)

*************************************************
Running validation on k = 2


Feature extraction: TFIDF

totalMat: 
[[ 2815.   356.]
 [  420.  2708.]]
total: 
0.876805842197
Feature extraction: Token Count


totalMat: 
[[ 2409.   762.]
 [  705.  2423.]]
total: 
0.767105889824
*************************************************
Running validation on k = 3


Feature extraction: TFIDF

totalMat: 
[[ 1967.  1204.]
 [  259.  2869.]]
total: 
0.767740911256
Feature extraction: Token Count


totalMat: 
[[ 2454.   717.]
 [  631.  2497.]]
total: 
0.785997777425
*************************************************
Running validation on k = 10


Feature extraction: TFIDF

totalMat: 
[[ 2799.   372.]
 [  261.  2867.]]
total: 
0.89950785839
Feature extraction: Token Count


totalMat: 
[[ 2519.   652.]
 [  607.  2521.]]
total: 
0.800127004286
